name=Hijri_date
version=1.0.1
author=Fa'al
maintainer=Fa'al
sentence=A library for converting Gregorian dates to Hijri dates with multi-language (EN/ID) support.
paragraph=Hijri_date allows developers to easily calculate Islamic dates from Gregorian input. It features manual offset correction, supports global language selection (English/Indonesia), and works seamlessly on Arduino, ESP8266, and ESP32.
category=Data Processing
url=https://github.com/Fl-project123/Hijri_date
architectures=*
includes=Hijri_date.h
