name=Hijri_date
version=1.0.0
author=Fa'al
maintainer=Fa'al
sentence=A library for converting Gregorian dates to Hijri dates using the Tabular algorithm.
paragraph=Hijri_date allows developers to easily calculate Islamic dates from Gregorian input. It features manual offset correction and supports ESP8266/ESP32 for IoT projects like digital prayer clocks.
category=Data Processing
url=https://github.com/Fl-project123/Hijri_date
architectures=*
includes=Hijri_date.h